### ISSUE TITLE
Bug regarding setting units

### ISSUE THREAD

**Issue by JustAnotherSupporter** [vishnuraghavb/EnRecipes#1]
First and foremost - wonderful application!

Changing units from the standard "unit" to any other value such as "g", "tbsp" ect. doesn't register when saving the recipe, and the value resets.

The amount of added ingredients or set serving sizes doesn't change anything.
Modifying the exported and unpacked recipes.json from "unit":"unit" to "unit":"kg", repacking and successfully importing doesn't change the value in the app.

V. 1.1.2 from f-droid installed on 2020-12-07.
Android v. 10 with one UI v. 2.5  on top.

**Comment by vishnuraghavb** [comment]
Thank for reporting this issue! Don't know how I missed it.
In the last update, it has included app translations so that might have ruined something. 
It'll be fixed soon (possibly tonight) and I'll update you soon.

**Comment by vishnuraghavb** [comment]
@JustAnotherSupporter The bug has been fixed!
Please install the latest apk from [here](https://github.com/vishnuraghavb/EnRecipes/releases/tag/v1.1.3)

**Comment by JustAnotherSupporter** [comment]
Works flawlessly!
Thanks for the quick fix!
