### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by rugk** [vishnuraghavb/EnRecipes#15]
**Please check the [roadmap](https://github.com/vishnuraghavb/EnRecipes/projects/1) for upcoming features before proceeding**
- [X] I've checked the roadmap and my feature request is not listed there

**Is your feature request related to a problem? Please describe.**
I want to use F-Droid from scratch (directly after installation) and find/install the app.

**Describe the solution you'd like**
It would be great to see this Android app on F-Droid!

[F-Droid](https://f-droid.org/) is an Android app store specifically for free/libre open-source apps. It would be great if your app could be released there, as it is the number one for getting FLOSS Android apps for many people.
F-Droid also builds all apps from source ([optionally even reproducible](https://f-droid.org/en/docs/Reproducible_Builds/)), so downloads from there can be trusted.

The [app developer FAQ](https://f-droid.org/en/docs/FAQ_-_App_Developers/) or [the quick start guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) may help you to get started.

**Describe alternatives you've considered**
I've heard your app is already released on Izzi's repo, so pinging @IzzySoft. Of course, an "official" release on the main repo would be much better than the in-official release.

**Additional context**
previous discussion: https://chaos.social/@rugk/105476745013474133

**Comment by IzzySoft** [comment]
See https://gitlab.com/fdroid/rfp/-/issues/1570 – Vishnu already started that process 4 weeks ago. RFP has meanwhile successfully passed, so the next step is opening a merge request at fdroiddata with the YAML metadata prepared at the end of the RFP process.

**Comment by vishnuraghavb** [comment]
@IzzySoft I was thinking that you'll be the one responsible to bring the app into the main repo. I didn't know that I should repeat the process on the main f-droid repo as well. Anyways, I'll try my luck to create a MR on fdroid repo with your YAML file. Thanks for the info.

**Comment by IzzySoft** [comment]
Just to clarify: You've opened an RFP already and thus triggered the process for the "main repo". This usually suffices, if all goes well. It's just we're permanently understaffed at F-Droid (something I'm currently working on, "recruiting" and training new contributors/reviewers), so the more you can do the faster it will go. If you open the MR, we'll meet there. If you don't, at some point one of the packagers (might be me) will pick it up from RFP and open the MR for you, it will just take a bit longer.

So what I meant was: the MR is the next step to be taken. I didn't explicitly state by whom :laughing:

**Comment by vishnuraghavb** [comment]
Now I get it. I thought it was a different process (sorry, I couldn't understand at first). 
Meanwhile, I've gone through the documentation to include a new app on f-droid. Since this is a NativeScript based Android app, I don't know how to setup the .yml file for it (TBH couldn't find any resources online). So I'll leave it to the pros like you 😉 and I'll wait till you do it.

**Comment by IzzySoft** [comment]
Thanks for the :bouquet: but unfortunately I'm no "pro" in that area (I'm rather a "junior packager", started on that front only a few weeks ago) – especially when it comes to things like NativeScript (I'll never understand how Javascript can be called "Native" or what the person smoked when they created that name – and no, I'm not sure if I want some of that :speak_no_evil: :rofl:). So we'll have to leave it to someone who does know, sorry.

**Comment by vishnuraghavb** [comment]
Ok I understand and I request you to know about NativeScript(It is not entirely Javascript though as you think). For the app inclusion, I'll try again and let me see if I can figure it out by myself.

**Comment by IzzySoft** [comment]
Thanks Vishnu – if you can get it rolling, that would be great. If during that process you take some notes and end up with a kind of "check-list", that might be helpful! You could post it somewhere (e.g. a Gist here at Github) and I could link it from my F-Droid snippets for interested folks to find. If it's relatively easy to follow, I'll certainly pick up on it – but please understand that my time isn't without limits and I cannot be everywhere, so one thing at a time :wink:

**Comment by vishnuraghavb** [comment]
Sure Izzy, I was already thinking to do that(the check-list) and share it with you actually. I'm feeling positive that it's going to be easier with NativeScript. I'll let you know the results soon 👍🏽

**Comment by nautilusx** [comment]
@vishnuraghavb Congratulations, your app is now available on F-Droid. (https://f-droid.org/packages/com.vishnuraghav.EnRecipes/)

So you can close this issue.

**Comment by vishnuraghavb** [comment]
@nautilusx Thanks for the good news!
