### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by ruralTom** [vishnuraghavb/EnRecipes#28]
**Please check the [roadmap](https://github.com/vishnuraghavb/EnRecipes/projects/1) for upcoming features before proceeding**
- [ x ] I've checked the roadmap and my feature request is not listed there

**Is your feature request related to a problem? Please describe.**
The units for ingredients don't allow for fractionals. A recipe may call for 2 1/2 cups of an ingredient or, 1/8th of a tsp.

**Describe the solution you'd like**
A way to put in frational measurements.

**Describe alternatives you've considered**
N/A 

**Additional context**

**Comment by ruralTom** [comment]
This might be an annoying American imperial measurement thing. I don't know.

My only defense is it's England's system, I'm just stuck with it.

**Comment by vishnuraghavb** [comment]
Hello @ruralTom, I've added your request to the [roadmap](https://github.com/vishnuraghavb/EnRecipes/projects/1#card-53582809l). It'll be implemented soon 👍🏽
 Thanks!
