### ISSUE TITLE
No app name in launcher

### ISSUE THREAD

**Issue by vishnuraghavb** [vishnuraghavb/EnRecipes#29]
There has been a mistake setting up Weblate translations, because of this, app name doesn't show up for French and Italian language users.
It'll be fixed soon!

**Comment by mondlicht-und-sterne** [comment]
in the kisslauncher it shows the enrecipes icon correctly.
you can see my self-painted acrylic picture of my own icon pack (also available in the fdroid store).

![enrecipeslauncher](https://user-images.githubusercontent.com/61406324/107145315-e2461800-6940-11eb-8d8a-e933a1784442.jpg)

**Comment by vishnuraghavb** [comment]
Fixed in [v1.3.2 release](https://github.com/vishnuraghavb/EnRecipes/releases/tag/v1.3.2)
