### ISSUE TITLE
[BUG] improvements

### ISSUE THREAD

**Issue by farfromrefug** [vishnuraghavb/EnRecipes#33]
first great app love your work!
secondly thanks for opening the door for fdroid and nativescript devs. you helped us all a lot.

now I though I would bring up a few remarks.
your settings page is too slow to open :
* you should use a listview instead of a scroll view. it would help a lot (less views created)
* drop mdripple. instead use [this](https://github.com/nativescript-community/ui-material-components/blob/master/src/core/index.d.ts#L57). then simply use the rippleColor property on any view.
* be careful with labels. they are pretty slow. and you use a lot of them. you could use `@nativescript-community/ui-canvaslabel`.
*  you should switch from N ListView to `@nativescript-community/ui-collectionview`. much faster as using newer native widgets

I can help you even more like with faster localization and such.
let me know I'd you are interested

**Comment by vishnuraghavb** [comment]
Thank you for your nice words! 😊 And thanks a lot for the great recommendations, I'll definitely take everything you have mentioned here for the next update. Even I was struggling to speed up the app in all the ways possible. I'm very glad that you are here to help 😃 

> I can help you even more like with faster localization and such.
let me know I'd you are interested
Of course I will need experts like you to better this project.

**Comment by farfromrefug** [comment]
ok we should chat on slack or discord will be easier. are on N community in one of those ?

**Comment by vishnuraghavb** [comment]
I'm not on either of the platforms but [Telegram](https://t.me/vishnuraghavb).
Should I join slack using this link: https://nativescriptcommunity.slack.com/signup#/?

**Comment by vishnuraghavb** [comment]
Just now joined the discord channel and have pinged you!

**Comment by vishnuraghavb** [comment]
Thanks for your suggestions! I've tried my best to implement everything except **ui-canvaslabel** (which I couldn't format it properly because of several text verticalAlignment:middle). I'll definitely consider this plugin for other purposes in the future.
Released as [v1.3.2](https://github.com/vishnuraghavb/EnRecipes/releases/tag/v1.3.2)
