### ISSUE TITLE
[DEP] `nativescript-couchbase-plugin` moved

### ISSUE THREAD

**Issue by FestplattenSchnitzel** [vishnuraghavb/EnRecipes#36]
Seems like `nativescript-couchbase-plugin` is now `@triniwiz/nativescript-couchbase`.
See https://github.com/triniwiz/nativescript-couchbase-plugin#nativescript-couchbase

[EDIT]: You probably want to check the other plugins of **triniwiz** as well. `nativescript-accelerometer` seems to be affected too.

**Comment by vishnuraghavb** [comment]
Thanks for letting me know! I've updated all the packages to latest. Will release an update soon!

**Comment by vishnuraghavb** [comment]
Fixed in [v1.3.2 release](https://github.com/vishnuraghavb/EnRecipes/releases/tag/v1.3.2)
