### ISSUE TITLE
[FEATURE REQUEST] Being able to rearrange the order of ingredients/instructions afterwards

### ISSUE THREAD

**Issue by JustAnotherSupporter** [vishnuraghavb/EnRecipes#89]
**Please check the [roadmap](https://github.com/vishnuraghavb/EnRecipes/projects/1) for upcoming features before proceeding**
- [x] I've checked the roadmap and my feature request is not listed there

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

----

It would be a nice feature to be able to rearrange the order of the individual input fields after it has been filled in. I imagine that it would be useful when one (read I) forgets to add an ingredient early on and only see this after having finished creating the recipe.
An implementation like the one [OmGodse has made in Notally](https://github.com/OmGodse/Notally) when dragging items on a list could maybe be used as inspiration?

Keep up the stellar work!

**Comment by vishnuraghavb** [comment]
Hi, I've already implemented an [enhancement](https://github.com/vishnuraghavb/EnRecipes/projects/1#card-63935574) (not exactly like you said though) that could solve this issue on my development build and will be released soon.
And thanks for the example! I see that it is a native android app built using Kotlin which uses native components to implement drag and drop of list items. But here with EnRecipes which uses NativeScript, is quite difficult to replicate the same. So for now I'll move your suggestion to the roadmap for me to implement it in the future. But for now, my current implementation should solve the issue. Stay tuned for the next update!
